# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
#parameters:
#    slack_token: "%slackbot.apitoken%"

services:
    api:
        class: AppBundle\Helper\ApiFactory
        arguments: ["@logger"]
    slackbot:
        class: AppBundle\Helper\SlackBot
        arguments: ["@logger", "%slackbot.apitoken%"]
