AppBundle\Entity\ScheduleAppointment:
    type: entity
    table: appointments
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        time:
            type: time
        username:
            type: string
            length: 80
            nullable: true
    manyToOne:
        day:
            targetEntity: ScheduleDay
            inversedBy: appointments
            joinColumn:
                name: day_id
                referencedColumnName: id