AppBundle\Entity\ScheduleDay:
    type: entity
    repositoryClass: AppBundle\Entity\ScheduleDayRepository
    table: days
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        date:
            type: date
    oneToMany:
        appointments:
            orderBy: { 'time': 'ASC' }
            targetEntity: ScheduleAppointment
            mappedBy: day