<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ScheduleDayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScheduleDayRepository extends EntityRepository {
	public function getWeek(\DateTime $start, \DateTime $end) {
		$queryBuilder = $this->createQueryBuilder('s');
		$query = $queryBuilder
			->andWhere($queryBuilder->expr()->between('s.date', ':date_from', ':date_to'))
			->setParameter('date_from', $start, \Doctrine\DBAL\Types\Type::DATETIME)
			->setParameter('date_to', $end, \Doctrine\DBAL\Types\Type::DATETIME)
			->getQuery();

		return $query->getResult();
	}
}
